Add check to RTL repo sync workflow

diff --git a/.github/workflows/rtl-repo-sync.yml b/.github/workflows/rtl-repo-sync.yml
--- a/.github/workflows/rtl-repo-sync.yml
+++ b/.github/workflows/rtl-repo-sync.yml
@@ -11,6 +11,7 @@ jobs:
     outputs:
       branch_name: ${{ steps.branch.outputs.branch }}
       ci_checks_needed: ${{ steps.status.outputs.status }}
+      branch_base_ref: ${{ steps.commit.outputs.branch_base_ref }}
     steps:
       - name: Get current date
         id: date
@@ -43,10 +44,12 @@ jobs:
 
       # If there's a new HW release (submodule has been updated), add a commit to main branch
       - name: Commit changes
+        id: commit
         if: ${{ steps.status.outputs.status }}
         run: |
           git config --global user.name "GitHub CI"
           git config --global user.email "username@users.noreply.github.com"
+          echo "branch_base_ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
           git checkout -b ${{ steps.branch.outputs.branch }}
           git commit -a -m "CI: Update Caliptra RTL"
           git push -u origin ${{ steps.branch.outputs.branch }}
@@ -100,6 +103,10 @@ jobs:
         run: |
           git config --global user.name "GitHub CI"
           git config --global user.email "username@users.noreply.github.com"
+          if [[ "${{ needs.update-rtl.outputs.branch_base_ref }}" != $(git rev-parse HEAD) ]]; then
+              echo "Commit added to main after CI RTL branch test started; cannot auto-merge branch"
+              exit 1
+          fi
           git merge origin/${{ needs.update-rtl.outputs.branch_name }}
           git push
           git push origin --delete ${{ needs.update-rtl.outputs.branch_name }}
